const RSS2JSON_API = "https://api.rss2json.com/v1/api.json?rss_url=";

export const FEED_SOURCES = [
	// --- EXPANSÃO CONTÍNUA ---
	{
		url: "https://www.themarysue.com/feed/",
		category: "Entretenimento",
	},
	{ url: "https://www.mobiletime.com.br/feed/", category: "Tecnologia" },
	{ url: "https://www.freecodecamp.org/news/rss/", category: "Tecnologia" },
	{ url: "https://9to5google.com/feed/", category: "Tecnologia" },
	{ url: "https://news.mit.edu/rss/feed", category: "Tecnologia" },
	{ url: "https://lobste.rs/rss", category: "Tecnologia" },
	{ url: "https://davidwalsh.name/feed", category: "Tecnologia" },
	{
		url: "https://feeds.folha.uol.com.br/ciencia/rss091.xml",
		category: "Ciência",
	},
	{ url: "https://feed.infoq.com/", category: "Tecnologia" },
	{
		url: "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
		category: "Ciência",
	},
	{ url: "https://blog.google/rss/", category: "Tecnologia" },
	{
		url: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
		category: "Ciência",
	},
	{
		url: "https://rss.nytimes.com/services/xml/rss/nyt/Space.xml",
		category: "Ciência",
	},
	{ url: "https://www.pushsquare.com/feeds/latest", category: "Games" },
	{ url: "https://dev.to/feed", category: "Tecnologia" },
	{ url: "https://hnrss.org/frontpage", category: "Tecnologia" },
	{ url: "https://www.technologyreview.com/feed/", category: "Tecnologia" },
	{ url: "https://www.androidpolice.com/feed/", category: "Tecnologia" },
	{ url: "https://www.bgr.com/feed/", category: "Tecnologia" },
	{ url: "https://feeds.npr.org/1007/rss.xml", category: "Ciência" },
	{
		url: "https://www.techrepublic.com/rssfeeds/articles/",
		category: "Tecnologia",
	},
	{
		url: "https://rss.nytimes.com/services/xml/rss/nyt/Americas.xml",
		category: "Mundo",
	},
	{ url: "https://g1.globo.com/rss/g1/ciencia/", category: "Ciência" },
	{ url: "https://g1.globo.com/rss/g1/saude/", category: "Saúde" },
	{ url: "https://g1.globo.com/rss/g1/fato-ou-fake/", category: "Brasil" },
	{
		url: "https://g1.globo.com/rss/g1/economia/agronegocios/",
		category: "Negócios",
	},
	{ url: "https://g1.globo.com/rss/g1/meio-ambiente/", category: "Ciência" },
	{ url: "https://g1.globo.com/rss/g1/loterias/", category: "Brasil" },
	{
		url: "https://g1.globo.com/rss/g1/trabalho-e-carreira/",
		category: "Negócios",
	},
	{
		url: "https://noticiasdatv.uol.com.br/feed",
		category: "Entretenimento",
	},
	{ url: "https://www.infomoney.com.br/feed/", category: "Negócios" },
	{
		url: "https://feeds.elpais.com/mrss-s/pages/ep/site/brasil.elpais.com/portada",
		category: "Mundo",
	},
	{
		url: "https://www.correiobraziliense.com.br/rss/noticia/tecnologia/rss.xml",
		category: "Tecnologia",
	},
	{ url: "https://olhardigital.com.br/feed/", category: "Tecnologia" },
	{ url: "https://vidadestartup.org/feed/", category: "Startups" },
	{ url: "https://tiinside.com.br/feed/", category: "Tecnologia" },
	{ url: "https://g1.globo.com/rss/g1/brasil/", category: "Brasil" },
	{
		url: "https://feeds.folha.uol.com.br/mercado/rss091.xml",
		category: "Negócios",
	},
	{
		url: "https://feeds.folha.uol.com.br/ilustrada/rss091.xml",
		category: "Entretenimento",
	},
	{
		url: "https://feeds.folha.uol.com.br/esporte/rss091.xml",
		category: "Esportes",
	},
	{
		url: "https://feeds.folha.uol.com.br/cotidiano/rss091.xml",
		category: "Brasil",
	},
	{
		url: "https://feeds.folha.uol.com.br/educacao/rss091.xml",
		category: "Educação",
	},
	{
		url: "https://feeds.folha.uol.com.br/tec/rss091.xml",
		category: "Tecnologia",
	},
	{
		url: "https://feeds.folha.uol.com.br/ambiente/rss091.xml",
		category: "Ciência",
	},
	{
		url: "https://feeds.folha.uol.com.br/equilibrioesaude/rss091.xml",
		category: "Saúde",
	},
	{
		url: "https://feeds.folha.uol.com.br/turismo/rss091.xml",
		category: "Geral",
	},
	{
		url: "https://feeds.folha.uol.com.br/comida/rss091.xml",
		category: "Geral",
	},
	{ url: "https://rss.uol.com.br/feed/economia.xml", category: "Negócios" },
	{ url: "https://rss.uol.com.br/feed/tecnologia.xml", category: "Tecnologia" },
	{ url: "https://rss.uol.com.br/feed/carros.xml", category: "Automóveis" },
	{ url: "https://rss.uol.com.br/feed/jogos.xml", category: "Tecnologia" },
	{ url: "https://rss.uol.com.br/feed/educacao.xml", category: "Educação" },
	// --- EXPANSÃO CONTÍNUA ---
	{ url: "https://feeds.npr.org/1004/rss.xml", category: "Mundo" },
	{ url: "https://g1.globo.com/rss/g1/natureza/", category: "Ciência" },
	{ url: "https://g1.globo.com/rss/g1/pop-arte/", category: "Entretenimento" },
	{ url: "https://g1.globo.com/rss/g1/carros/", category: "Automóveis" },
	{ url: "https://jornaldebrasilia.com.br/feed/", category: "Brasil" },
	{ url: "https://www.band.uol.com.br/rss", category: "Geral" },
	{ url: "https://jornal.usp.br/feed/", category: "Brasil" },
	{ url: "https://www.poder360.com.br/feed/", category: "Brasil" },
	// --- TECNOLOGIA (MUNDO) ---
	{ url: "https://meiobit.com/feed/", category: "Tecnologia" },
	{ url: "https://techcrunch.com/feed/", category: "Tecnologia" },
	{ url: "https://www.theverge.com/rss/index.xml", category: "Tecnologia" },
	{ url: "https://arstechnica.com/feed/", category: "Tecnologia" },
	{ url: "https://www.engadget.com/rss.xml", category: "Tecnologia" },
	{ url: "https://www.cnet.com/rss/news/", category: "Tecnologia" },
	{ url: "https://www.zdnet.com/news/rss.xml", category: "Tecnologia" },
	{ url: "https://www.techradar.com/rss", category: "Tecnologia" },
	{
		url: "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
		category: "Tecnologia",
	},
	{
		url: "https://feeds.bbci.co.uk/news/technology/rss.xml",
		category: "Tecnologia",
	},
	{ url: "https://rss.slashdot.org/Slashdot/slashdot", category: "Tecnologia" },
	{ url: "https://news.ycombinator.com/rss", category: "Tecnologia" },
	{ url: "https://venturebeat.com/feed/", category: "Tecnologia" },
	{ url: "https://readwrite.com/feed/", category: "Tecnologia" },
	{ url: "https://thenextweb.com/feed/", category: "Tecnologia" },
	{ url: "https://mashable.com/feed/", category: "Tecnologia" },
	{ url: "https://gizmodo.com/rss", category: "Tecnologia" },
	{
		url: "https://www.gizmodo.com.br/feed",
		category: "Tecnologia",
		company: "Gizmodo Brasil",
	},
	{ url: "https://9to5mac.com/feed/", category: "Tecnologia" },
	{ url: "https://www.macrumors.com/macrumors.xml", category: "Tecnologia" },
	{ url: "https://www.androidauthority.com/feed/", category: "Tecnologia" },
	{ url: "https://www.androidcentral.com/feed", category: "Tecnologia" },
	{ url: "https://www.theinformation.com/feed", category: "Tecnologia" },
	{ url: "https://spectrum.ieee.org/rss/computing", category: "Tecnologia" },
	{ url: "https://www.extremetech.com/feed", category: "Tecnologia" },
	{ url: "https://www.tomshardware.com/feeds/all", category: "Tecnologia" },
	{ url: "https://www.anandtech.com/rss/", category: "Tecnologia" },
	{
		url: "https://feeds.feedburner.com/TechCrunch/startups",
		category: "Tecnologia",
	},
	{ url: "https://www.smashingmagazine.com/feed", category: "Tecnologia" },
	{ url: "https://hackernoon.com/feed", category: "Tecnologia" },
	{ url: "https://www.sitepoint.com/feed", category: "Tecnologia" },
	{ url: "https://www.sciencealert.com/feed", category: "Tecnologia" },
	{ url: "https://www.theregister.com/headlines.atom", category: "Tecnologia" },
	{ url: "https://www.bleepingcomputer.com/feed/", category: "Tecnologia" },
	{ url: "https://krebsonsecurity.com/feed/", category: "Tecnologia" },
	{ url: "https://threatpost.com/feed/", category: "Tecnologia" },

	// --- TECNOLOGIA (BRASIL) ---
	{ url: "https://rss.tecmundo.com.br/feed", category: "Tecnologia" },
	{ url: "https://canaltech.com.br/rss/", category: "Tecnologia" },
	{ url: "https://canaltech.com.br/rss/produtos", category: "Tecnologia" },
	{ url: "https://teletime.com.br/feed/", category: "Tecnologia" },
	{ url: "https://olhardigital.com.br/rss", category: "Tecnologia" },
	{ url: "https://tecnoblog.net/feed/", category: "Tecnologia" },
	{ url: "https://mundoconectado.com.br/feed/", category: "Tecnologia" },
	{ url: "https://www.tudocelular.com/rss/", category: "Tecnologia" },
	{ url: "https://macmagazine.com.br/feed/", category: "Tecnologia" },
	{ url: "https://manualdousuario.net/feed/", category: "Tecnologia" },
	{ url: "https://computerworld.com.br/feed/", category: "Tecnologia" },
	{ url: "https://itforum.com.br/feed/", category: "Tecnologia" },
	{ url: "https://imasters.com.br/feed", category: "Tecnologia" },
	{ url: "https://www.wired.com/feed/rss", category: "Tecnologia" },
	{ url: "https://g1.globo.com/rss/g1/tecnologia/", category: "Tecnologia" },
	{ url: "https://nucleo.jor.br/feed/", category: "Tecnologia" },
	{ url: "https://mittechreview.com.br/feed/", category: "Tecnologia" },
	{ url: "https://www.hardware.com.br/feed/", category: "Tecnologia" },
	{ url: "https://adrena.me/feed/", category: "Tecnologia" },
	{ url: "https://www.showmetech.com.br/feed/", category: "Tecnologia" },
	{ url: "https://www.oficinadanet.com.br/rss.xml", category: "Tecnologia" },

	// --- INTELIGÊNCIA ARTIFICIAL ---
	{ url: "https://www.unite.ai/feed/", category: "IA" },
	{ url: "https://blogs.nvidia.com/feed/", category: "IA" },
	{ url: "https://openai.com/blog/rss.xml", category: "IA" },
	{ url: "https://www.artificialintelligence-news.com/feed/", category: "IA" },
	{ url: "https://datanami.com/feed/", category: "IA" },
	{ url: "https://www.marktechpost.com/feed/", category: "IA" },
	{ url: "https://www.kdnuggets.com/feed", category: "IA" },
	{ url: "https://mit-press.mit.edu/feed", category: "IA" },
	{ url: "https://stability.ai/blog/rss", category: "IA" },
	{ url: "https://www.deepmind.com/blog/rss.xml", category: "IA" },
	{ url: "https://news.microsoft.com/source/feed/", category: "IA" },
	{ url: "https://ai.googleblog.com/atom.xml", category: "IA" },
	{
		url: "https://aws.amazon.com/blogs/machine-learning/feed/",
		category: "IA",
	},
	{ url: "https://machinelearningmastery.com/feed/", category: "IA" },
	{ url: "https://towardsdatascience.com/feed", category: "IA" },

	// --- BRASIL ---
	{ url: "https://g1.globo.com/rss/g1/", category: "Brasil" },
	{ url: "https://www.tse.jus.br/rss", category: "Brasil" },
	{
		url: "https://www.em.com.br/rss/noticia/politica/rss.xml",
		category: "Brasil",
	},
	{ url: "https://www.otempo.com.br/rss/politica", category: "Brasil" },
	{ url: "https://gauchazh.clicrbs.com.br/rss/", category: "Brasil" },
	{ url: "https://www.jota.info/feed", category: "Brasil" },
	{ url: "https://g1.globo.com/rss/g1/politica/", category: "Brasil" },
	{ url: "https://oantagonista.uol.com.br/feed/", category: "Brasil" },
	{ url: "https://rss.uol.com.br/feed/noticias.xml", category: "Brasil" },
	{
		url: "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml",
		category: "Brasil",
	},
	{
		url: "https://feeds.folha.uol.com.br/poder/rss091.xml",
		category: "Brasil",
	},
	{ url: "https://www.cnnbrasil.com.br/feed/", category: "Brasil" },
	{ url: "https://www.estadao.com.br/rss/ultimas", category: "Brasil" },
	{ url: "https://www.poder360.com.br/feed", category: "Brasil" },
	{ url: "https://www.cartacapital.com.br/feed/", category: "Brasil" },
	{ url: "https://www.bbc.com/portuguese/index.xml", category: "Brasil" },
	{ url: "https://veja.abril.com.br/feed/", category: "Brasil" },
	{ url: "https://www.terra.com.br/rss/noticias", category: "Brasil" },
	{
		url: "https://agenciabrasil.ebc.com.br/rss/ultimasnoticias/feed.xml",
		category: "Brasil",
	},
	{ url: "https://istoe.com.br/feed/", category: "Brasil" },
	{ url: "https://www.em.com.br/rss/noticias/", category: "Brasil" },
	{ url: "https://www.diariodepernambuco.com.br/rss/", category: "Brasil" },
	{
		url: "https://www.correiobraziliense.com.br/rss/noticias",
		category: "Brasil",
	},
	{ url: "https://www.opovo.com.br/rss/noticias", category: "Brasil" },
	{ url: "https://www.otempo.com.br/rss/noticias", category: "Brasil" },
	{ url: "https://www.nsctotal.com.br/feed", category: "Brasil" },
	{ url: "https://www.gazetadopovo.com.br/feed/", category: "Brasil" },
	{ url: "https://www.metropoles.com/feed", category: "Brasil" },
	{
		url: "https://noticias.uol.com.br/ultimas-noticias/rss.xml",
		category: "Geral",
	},
	{
		url: "https://www.em.com.br/rss/noticia/gerais/rss.xml",
		category: "Geral",
	},
	{
		url: "https://www.correiobraziliense.com.br/rss/noticia/brasil/rss.xml",
		category: "Geral",
	},
	{ url: "https://www.jb.com.br/rss.xml", category: "Geral" },
	{ url: "https://www.gazetadopovo.com.br/rss/", category: "Geral" },
	{ url: "https://congressoemfoco.uol.com.br/feed/", category: "Brasil" },
	{ url: "https://www.brasil247.com/feed", category: "Brasil" },
	{ url: "https://www.diariodocentrodomundo.com.br/feed/", category: "Brasil" },
	{ url: "https://revistaforum.com.br/feed", category: "Brasil" },
	{ url: "https://www.conjur.com.br/rss.xml", category: "Brasil" },
	{ url: "https://oglobo.globo.com/rss/brasil.xml", category: "Brasil" },
	{ url: "https://oglobo.globo.com/rss/economia.xml", category: "Brasil" },
	{ url: "https://g1.globo.com/rss/g1/educacao/", category: "Brasil" },
	{ url: "https://apublica.org/feed/", category: "Brasil" },
	{ url: "https://joioeotrigo.com.br/feed/", category: "Brasil" },
	{ url: "https://br.noticias.yahoo.com/rss", category: "Brasil" },
	{ url: "https://agenciapublica.org/feed/", category: "Brasil" },
	{ url: "https://piaui.folha.uol.com.br/feed/", category: "Brasil" },
	{ url: "https://www.sbtnews.com.br/rss.xml", category: "Brasil" },
	{ url: "https://jovempan.com.br/feed", category: "Brasil" },
	{
		url: "https://www.gazetadopovo.com.br/feed/rss/brasil.xml",
		category: "Brasil",
	},
	{ url: "https://diplomatique.org.br/feed/", category: "Brasil" },
	{ url: "https://guiadoestudante.abril.com.br/feed/", category: "Brasil" },
	{ url: "https://www.nexojornal.com.br/rss.xml", category: "Brasil" },
	{ url: "https://revistaforum.com.br/feed/", category: "Brasil" },
	{ url: "https://www.brasildefato.com.br/rss2.xml", category: "Brasil" },

	// --- MUNDO ---
	{ url: "https://www.rfi.fr/br/rss", category: "Mundo" },
	{
		url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
		category: "Mundo",
	},
	{
		url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
		category: "Mundo",
	},
	{ url: "https://feeds.bbci.co.uk/news/world/rss.xml", category: "Mundo" },
	{ url: "https://feeds.bbci.co.uk/news/rss.xml", category: "Mundo" },
	{ url: "http://feeds.foxnews.com/foxnews/world", category: "Mundo" },
	{ url: "https://www.aljazeera.com/xml/rss/all.xml", category: "Mundo" },
	{ url: "https://feeds.reuters.com/reuters/worldNews", category: "Mundo" },
	{ url: "https://www.theguardian.com/world/rss", category: "Mundo" },
	{ url: "https://feeds.washingtonpost.com/rss/world", category: "Mundo" },
	{ url: "https://rss.cnn.com/rss/edition.rss", category: "Mundo" },
	{ url: "https://feeds.npr.org/1001/rss.xml", category: "Mundo" },
	{ url: "https://www.france24.com/en/rss", category: "Mundo" },
	{ url: "https://rss.dw.com/rdf/rss-br-all", category: "Mundo",
	},
	{
		url: "https://news.un.org/feed/subscribe/pt/news/all/rss.xml",
		category: "Mundo",
	},
	{ url: "https://apnews.com/hub/ap-top-news?format=rss", category: "Mundo" },
	{ url: "https://www.independent.co.uk/news/world/rss", category: "Mundo" },
	{ url: "https://feeds.folha.uol.com.br/mundo/rss091.xml", category: "Mundo" },
	{ url: "https://www.rtp.pt/noticias/rss/mundo", category: "Mundo" },
	{ url: "https://pt.euronews.com/rss?format=xml", category: "Mundo" },
	{
		url: "https://www.huffpost.com/section/world-news/feed",
		category: "Mundo",
	},
	{ url: "https://www.cbsnews.com/latest/rss/world", category: "Mundo" },
	{ url: "https://g1.globo.com/rss/g1/mundo/", category: "Mundo",
	},
	{ url: "https://www.vox.com/rss/index.xml", etc: "Mundo" },
	{ url: "https://www.axios.com/feeds/feed.rss", category: "Mundo" },
	{ url: "https://time.com/feed/", category: "Mundo" },
	{ url: "https://www.politico.com/rss/politicopicks.xml", category: "Mundo" },
	{ url: "https://slate.com/feeds/all.rss", category: "Mundo" },

	// --- NEGÓCIOS & FINANÇAS ---
	{ url: "https://www.jornaldenegocios.pt/rss", category: "Negócios" },
	{ url: "https://feeds.bloomberg.com/markets/news.rss", category: "Negócios" },
	{
		url: "https://www.cnbc.com/id/10000664/device/rss/rss.html",
		category: "Negócios",
	},
	{ url: "https://exame.com/feed/", category: "Negócios" },
	{ url: "https://www.forbes.com/business/feed/", category: "Negócios" },
	{ url: "https://www.economist.com/business/rss.xml", category: "Negócios" },
	{ url: "https://www.valor.com.br/rss", category: "Negócios" },
	{ url: "https://investnews.com.br/feed/", category: "Negócios" },
	{ url: "https://www.moneytimes.com.br/feed/", category: "Negócios" },
	{ url: "https://braziljournal.com/feed/", category: "Negócios" },
	{ url: "https://neofeed.com.br/feed/", category: "Negócios" },
	{ url: "https://www.suno.com.br/feed/", category: "Negócios" },
	{
		url: "https://epocanegocios.globo.com/rss/ultimas/feed.xml",
		category: "Negócios",
	},
	{ url: "https://br.investing.com/rss/news.rss", category: "Negócios" },
	{ url: "https://g1.globo.com/rss/g1/economia/", category: "Negócios" },
	{ url: "https://www.wsj.com/xml/rss/3_7014.xml", category: "Negócios" },
	{ url: "https://www.ft.com/?format=rss", category: "Negócios" },
	{ url: "https://startupi.com.br/feed/", category: "Negócios" },
	{ url: "https://startups.com.br/feed/", category: "Negócios" },
	{ url: "https://www.wsj.com/xml/rss/3_7031.xml", category: "Negócios" },
	{ url: "https://www.cnnbrasil.com.br/feed/economia", category: "Negócios" },
	{
		url: "https://www.bloomberglinea.com.br/arc/outboundfeeds/rss/",
		category: "Negócios",
	},
	{ url: "https://einvestidor.estadao.com.br/feed/", category: "Negócios" },
	{ url: "https://www.suno.com.br/noticias/feed/", category: "Negócios" },
	{ url: "https://forbes.com.br/feed/", category: "Negócios" },
	{
		url: "https://revistapegn.globo.com/rss/ultimas/feed.xml",
		category: "Negócios",
	},
	{
		url: "https://valorinveste.globo.com/rss/valor-investe",
		category: "Negócios",
	},

	// --- CRIPTOMOEDAS ---
	{ url: "https://br.cointelegraph.com/rss", category: "Cripto" },
	{ url: "https://portaldobitcoin.uol.com.br/feed/", category: "Cripto" },
	{ url: "https://www.criptofacil.com/feed/", category: "Cripto" },
	{ url: "https://livecoins.com.br/feed/", category: "Cripto" },
	{
		url: "https://www.coindesk.com/arc/outboundfeeds/rss/",
		category: "Cripto",
	},
	{ url: "https://www.seudinheiro.com/feed/", category: "Negócios" },
	{ url: "https://cointelegraph.com/rss", category: "Cripto" },
	{ url: "https://decrypt.co/feed", category: "Cripto" },
	{ url: "https://99bitcoins.com/feed/", category: "Cripto" },
	{ url: "https://coinjournal.net/feed/", category: "Cripto" },
	{ url: "https://blog.coinbase.com/feed", category: "Cripto" },

	// --- CIÊNCIA & ESPAÇO ---
	{
		url: "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
		category: "Ciência",
	},
	{ url: "https://revistapesquisa.fapesp.br/feed/", category: "Ciência" },
	{ url: "https://www.jornaldaciencia.org.br/feed/", category: "Ciência" },
	{
		url: "https://www.nasa.gov/rss/dyn/breaking_news.rss",
		category: "Ciência",
	},
	{ id: "https://www.sciencedaily.com/rss/all.xml", category: "Ciência" },
	{
		url: "https://revistagalileu.globo.com/rss/ultimas/feed.xml",
		category: "Ciência",
	},
	{ id: "https://hypescience.com/feed/", category: "Ciência" },
	{ url: "https://g1.globo.com/rss/g1/ciencia-e-saude/", category: "Ciência" },
	{ id: "https://www.space.com/feeds/all", category: "Ciência" },
	{ id: "https://super.abril.com.br/feed/", category: "Ciência" },
	{ id: "https://www.nature.com/nature.rss", category: "Ciência" },
	{
		url: "https://www.nationalgeographicbrasil.com/rss.xml",
		category: "Ciência",
	},
	{ id: "https://www.newscientist.com/feed/home", category: "Ciência" },
	{ id: "https://phys.org/rss-feed", category: "Ciência" },
	{ id: "https://socientifica.com.br/feed", category: "Ciência" },
	{ id: "https://engenhariae.com.br/feed", ...}]]
