name: CI

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/juninmd/fast-news:latest

      - name: Trigger ArgoCD sync (Update app-charts)
        env:
          PAT: ${{ secrets.PAT }}
        if: env.PAT != ''
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions Bot"
          git clone https://${PAT}@github.com/juninmd/app-charts.git temp-charts
          cd temp-charts
          git commit --allow-empty -m "chore: trigger argocd sync for fast-news"
          git push origin main
